#!/usr/bin/env node
// packages/clients/axle/scripts/autopatch.js
// Channel selection and manifest synchronisation for the Axle plugin.
//
//   node scripts/autopatch.js --print                  show the resolved channel
//   node scripts/autopatch.js --write                  regenerate .mcp.json from channels.json
//   node scripts/autopatch.js --check                  CI: fail on any drift (no writes)
//   node scripts/autopatch.js --sync-pin --channel=production
//                                                      CD: advance a channel's contract pin
//                                                      to what the deployed hub reports
//
// The problem this exists to solve: `.mcp.json` is what Claude Code reads to reach the
// hub, and `channels.json` records which contract each channel was last known to
// serve. If the core team ships a new tool surface and nothing updates that pin, the
// plugin keeps working right up until it calls a tool whose schema changed — and the
// failure surfaces in a user's editor, far from the change that caused it.
//
// So the flow is:
//
//   CI   --check     .mcp.json must match channels.json exactly, and (when the channel
//                    is reachable) the deployed digest must match the pin. Read-only,
//                    so a pull request cannot pass by rewriting the thing being checked.
//   CD   --sync-pin  after a channel's deploy passes its smoke test, advance that
//                    channel's pin to the digest the hub is actually serving and commit
//                    it. The pin therefore always trails a *verified* deploy.
//   dev  --write     regenerate .mcp.json after switching channels locally.
//
// A `breaking` verdict (differing contract majors) is always a hard failure: no amount
// of manifest rewriting makes an incompatible client work, and pretending otherwise
// would ship a plugin that fails at the first tool call.

'use strict';

const fs = require('node:fs');
const path = require('node:path');

const { compareContract } = require('@pivotly/contract');
const { CONTRACT_VERSION, ENDPOINTS, CHANNELS, HARDENED_CHANNELS } = require('@pivotly/contract/protocol');
const { HEADERS, AUTH_SCHEME } = require('@pivotly/contract/auth');
const { contractDigest } = require('@pivotly/contract/digest');

// Normally the package directory. AXLE_MANIFEST_DIR redirects the manifests it reads
// and writes, which is how test/axle.test.js drives the real script against a scratch
// copy instead of the committed files — and how you can point it at another checkout.
const ROOT = process.env.AXLE_MANIFEST_DIR ? path.resolve(process.env.AXLE_MANIFEST_DIR) : path.join(__dirname, '..');
const CHANNELS_PATH = path.join(ROOT, 'channels.json');
const MCP_PATH = path.join(ROOT, '.mcp.json');
const SERVER_NAME = 'pivotly-hub';

const arg = (name, fallback = null) => {
  const hit = process.argv.find((a) => a.startsWith(`--${name}=`));
  return hit ? hit.slice(name.length + 3) : fallback;
};
const flag = (name) => process.argv.includes(`--${name}`);

const readJson = (p) => JSON.parse(fs.readFileSync(p, 'utf8'));
const writeJson = (p, body) => fs.writeFileSync(p, `${JSON.stringify(body, null, 2)}\n`);

function resolveChannel(manifest) {
  const name = arg('channel') || process.env.PIVOTLY_CHANNEL || manifest.default;
  if (!CHANNELS.includes(name)) {
    throw new Error(`unknown channel "${name}" — the contract declares ${CHANNELS.join(', ')}`);
  }
  const channel = manifest.channels[name];
  if (!channel) throw new Error(`channel "${name}" is declared by the contract but missing from channels.json`);
  return { name, ...channel };
}

// The generated .mcp.json. Built from the channel rather than hand-edited, so the URL
// Claude Code dials and the URL the pipeline verified are the same string.
//
// The token is referenced as ${ENV_VAR} and never inlined: this file is committed, and
// a plugin manifest is exactly the wrong place for a credential.
function mcpConfigFor(channel) {
  return {
    _comment:
      `GENERATED by scripts/autopatch.js from channels.json (channel: ${channel.name}). Do not hand-edit — run \`npm run autopatch -w @pivotly/axle\` instead, and note that CI fails if this file drifts from channels.json. The token is read from the ${channel.tokenEnv} environment variable at launch and is never written into this file.`,
    mcpServers: {
      [SERVER_NAME]: {
        type: 'http',
        url: channel.url,
        headers: {
          [HEADERS.auth]: `${AUTH_SCHEME} \${${channel.tokenEnv}}`,
          // Sent so the hub's logs can answer "which client versions are still
          // calling us", which is the question you need before retiring a contract.
          [HEADERS.channel]: channel.name,
          [HEADERS.clientContract]: channel.contractVersion,
        },
      },
    },
  };
}

const originOf = (url) => {
  const parsed = new URL(url);
  return `${parsed.protocol}//${parsed.host}`;
};

async function fetchDeployedIdentity(channel, timeoutMs) {
  const versionUrl = `${originOf(channel.url)}${ENDPOINTS.version}`;
  try {
    const res = await fetch(versionUrl, { signal: AbortSignal.timeout(timeoutMs) });
    if (!res.ok) return { reachable: false, reason: `${versionUrl} returned ${res.status}` };
    return { reachable: true, identity: await res.json(), versionUrl };
  } catch (err) {
    return { reachable: false, reason: `${versionUrl}: ${err.message}` };
  }
}

async function main() {
  const manifest = readJson(CHANNELS_PATH);
  const channel = resolveChannel(manifest);
  const timeoutMs = Number(arg('timeout-ms', '10000'));
  const problems = [];

  // --- structural checks, which need no network --------------------------
  if (channel.requireHttps !== false && !channel.url.startsWith('https://')) {
    problems.push(`channel "${channel.name}" requires https but its url is ${channel.url}`);
  }
  if (HARDENED_CHANNELS.includes(channel.name) && channel.requireHttps === false) {
    problems.push(`channel "${channel.name}" is a hardened channel and must not set requireHttps: false`);
  }
  if (!channel.url.endsWith(ENDPOINTS.mcp)) {
    problems.push(`channel "${channel.name}" url should end with the contract's MCP path (${ENDPOINTS.mcp}): ${channel.url}`);
  }
  if (!/^[0-9a-f]{12}$/.test(channel.contractDigest || '')) {
    problems.push(`channel "${channel.name}" has a malformed contractDigest: ${channel.contractDigest}`);
  }

  const expected = mcpConfigFor(channel);
  const current = fs.existsSync(MCP_PATH) ? readJson(MCP_PATH) : null;
  const inSync = current && JSON.stringify(current) === JSON.stringify(expected);

  if (flag('print')) {
    console.log(
      JSON.stringify(
        {
          channel: channel.name,
          url: channel.url,
          tokenEnv: channel.tokenEnv,
          pinnedContract: { version: channel.contractVersion, digest: channel.contractDigest },
          thisCheckout: { version: CONTRACT_VERSION, digest: contractDigest() },
          mcpJsonInSync: Boolean(inSync),
        },
        null,
        2
      )
    );
    return;
  }

  // --- write mode ---------------------------------------------------------
  if (flag('write')) {
    if (problems.length) {
      for (const p of problems) console.error(`FAIL  ${p}`);
      process.exitCode = 1;
      return;
    }
    writeJson(MCP_PATH, expected);
    console.log(`ok    .mcp.json ${inSync ? 'unchanged' : 'updated'} for channel "${channel.name}" -> ${channel.url}`);
    return;
  }

  // --- sync-pin mode (CD, after a verified deploy) -----------------------
  if (flag('sync-pin')) {
    const deployed = await fetchDeployedIdentity(channel, timeoutMs);
    if (!deployed.reachable) {
      console.error(`FAIL  cannot read the deployed contract: ${deployed.reason}`);
      console.error('      --sync-pin must never guess. The pin is only advanced from a hub that answered.');
      process.exitCode = 1;
      return;
    }

    const { contractVersion, contractDigest: deployedDigest } = deployed.identity;
    if (!/^[0-9a-f]{12}$/.test(deployedDigest || '')) {
      console.error(`FAIL  the deployed hub reported a malformed contract digest: ${deployedDigest}`);
      process.exitCode = 1;
      return;
    }

    // The deployed hub must be serving the contract in THIS checkout. If it is not,
    // the pipeline is mid-rollout or someone deployed from a different commit, and
    // advancing the pin would record a contract this client was never built against.
    if (deployedDigest !== contractDigest()) {
      console.error(`FAIL  the deployed hub serves contract ${deployedDigest} but this checkout builds ${contractDigest()}`);
      console.error('      Refusing to pin a contract this client was not built from. Re-run after the deploy for this commit completes.');
      process.exitCode = 1;
      return;
    }

    const unchanged = channel.contractDigest === deployedDigest && channel.contractVersion === contractVersion;
    manifest.channels[channel.name].contractDigest = deployedDigest;
    manifest.channels[channel.name].contractVersion = contractVersion;
    writeJson(CHANNELS_PATH, manifest);
    writeJson(MCP_PATH, mcpConfigFor({ ...channel, contractVersion }));

    console.log(
      unchanged
        ? `ok    channel "${channel.name}" pin already at ${deployedDigest} (${contractVersion}) — nothing to commit`
        : `ok    channel "${channel.name}" pin advanced to ${deployedDigest} (${contractVersion}), .mcp.json regenerated`
    );
    return;
  }

  // --- check mode (CI) ----------------------------------------------------
  // Read-only by design: a check that repaired what it was checking would let a pull
  // request pass by rewriting the evidence.
  if (!current) problems.push('.mcp.json does not exist — run: npm run autopatch -w @pivotly/axle -- --write');
  else if (!inSync) {
    problems.push(
      `.mcp.json has drifted from channels.json (channel "${channel.name}"). Run \`npm run autopatch -w @pivotly/axle -- --write\` and commit.`
    );
  }

  // The pin must describe the contract this repository builds. If it does not, someone
  // changed the tool surface without resyncing the client — the cascade this whole
  // mechanism exists to catch.
  const localVerdict = compareContract(
    { contractVersion: channel.contractVersion, contractDigest: channel.contractDigest },
    { contractVersion: CONTRACT_VERSION, contractDigest: contractDigest() }
  );
  if (localVerdict.verdict !== 'ok') {
    problems.push(
      `channel "${channel.name}" is pinned to contract ${channel.contractDigest} (${channel.contractVersion}) but this checkout builds ` +
        `${contractDigest()} (${CONTRACT_VERSION}) — ${localVerdict.reason}. ` +
        `The tool surface changed without updating the client manifest.`
    );
  }

  // Then, if the channel is actually reachable, check the deployed hub too. Being
  // unreachable is NOT a failure: a pull request from a fork has no network to Azure,
  // and CI must not depend on it. Only a reachable-and-wrong hub fails.
  const deployed = await fetchDeployedIdentity(channel, timeoutMs);
  if (!deployed.reachable) {
    console.log(`note  channel "${channel.name}" is not reachable from here, so the deployed digest was not checked (${deployed.reason})`);
  } else {
    const verdict = compareContract(
      { contractVersion: channel.contractVersion, contractDigest: channel.contractDigest },
      deployed.identity
    );
    if (verdict.verdict === 'breaking') {
      problems.push(`BREAKING: ${deployed.versionUrl} — ${verdict.reason}. This client cannot talk to that hub; it must be upgraded.`);
    } else if (verdict.verdict !== 'ok') {
      problems.push(
        `channel "${channel.name}" pin (${channel.contractDigest}) does not match the deployed hub ` +
          `(${deployed.identity.contractDigest}) — ${verdict.reason}. Run --sync-pin after the deploy has been verified.`
      );
    } else {
      console.log(`ok    deployed hub at ${deployed.versionUrl} serves the pinned contract ${deployed.identity.contractDigest}`);
      console.log(`ok    deployed commit ${deployed.identity.commit} on channel ${deployed.identity.channel}`);
    }
  }

  if (problems.length) {
    for (const p of problems) console.error(`FAIL  ${p}`);
    process.exitCode = 1;
    return;
  }
  console.log(`ok    channel "${channel.name}" is in sync — contract ${channel.contractDigest} (${channel.contractVersion})`);
}

module.exports = { mcpConfigFor, resolveChannel, SERVER_NAME, CHANNELS_PATH, MCP_PATH };

if (require.main === module) {
  main().catch((err) => {
    console.error(`FAIL  ${err.message}`);
    process.exit(1);
  });
}
