#!/usr/bin/env node
// packages/clients/scripts/generate.js
// Generates every client's config from ONE channel manifest and ONE contract.
//
//   node scripts/generate.js --print                     show the resolved channel
//   node scripts/generate.js --write                     regenerate every client config
//   node scripts/generate.js --write --client=axle       just one
//   node scripts/generate.js --check                     CI: fail on any drift (no writes)
//   node scripts/generate.js --sync-pin --channel=production
//                                                        CD: advance a channel's pin to
//                                                        what the deployed hub reports
//
// This is the multi-client story in one file. `CLIENTS` in the contract declares which
// clients exist and what format each one wants; a writer below turns the resolved
// channel into that format. Adding a client is a data change in the contract plus a
// writer here — never a second copy of the channel list, and never a hand-maintained
// config that can disagree with its siblings.
//
// The problem it solves: each client config is what its host reads to reach the hub,
// and channels.json records which contract each channel was last known to serve. If
// the core team ships a new tool surface and nothing updates those, the clients keep
// working right up until they call a tool whose schema changed — and the failure
// surfaces in a user's editor, far from the change that caused it.
//
//   CI   --check     configs must match the manifest exactly, and (when the channel is
//                    reachable) the deployed digest must match the pin. Read-only, so a
//                    pull request cannot pass by rewriting the thing being checked.
//   CD   --sync-pin  after a channel's deploy passes its smoke test, advance that pin to
//                    the digest the hub is actually serving. The pin therefore always
//                    trails a *verified* deploy.
//   dev  --write     regenerate after switching channels locally.

'use strict';

const fs = require('node:fs');
const path = require('node:path');

const { compareContract } = require('@pivotly/contract');
const { CONTRACT_VERSION, ENDPOINTS, HEADERS, CHANNELS, HARDENED_CHANNELS, CLIENTS, getClient } = require('@pivotly/contract/protocol');
const { contractDigest } = require('@pivotly/contract/digest');

// Normally the package directory. PIVOTLY_CLIENTS_DIR redirects what it reads and
// writes, which is how the tests drive the real script against a scratch copy instead
// of the committed files.
const ROOT = process.env.PIVOTLY_CLIENTS_DIR ? path.resolve(process.env.PIVOTLY_CLIENTS_DIR) : path.join(__dirname, '..');
const CHANNELS_PATH = path.join(ROOT, 'channels.json');
const SERVER_NAME = 'pivotly-hub';

const arg = (name, fallback = null) => {
  const hit = process.argv.find((a) => a.startsWith(`--${name}=`));
  return hit ? hit.slice(name.length + 3) : fallback;
};
const flag = (name) => process.argv.includes(`--${name}`);

const readJson = (p) => JSON.parse(fs.readFileSync(p, 'utf8'));

function resolveChannel(manifest) {
  const name = arg('channel') || process.env.PIVOTLY_CHANNEL || manifest.default;
  if (!CHANNELS.includes(name)) throw new Error(`unknown channel "${name}" — the contract declares ${CHANNELS.join(', ')}`);
  const channel = manifest.channels[name];
  if (!channel) throw new Error(`channel "${name}" is declared by the contract but missing from channels.json`);
  return { name, ...channel };
}

// The headers every client sends. No credential: the hub is anonymous by design. These
// are identity-of-caller metadata the hub logs, and they are what make "which client,
// on which channel, built against which contract" answerable — the question you have to
// answer before retiring a contract version, and with several clients you need to know
// which of them to chase.
const headersFor = (client, channel) => ({
  [HEADERS.client]: client.id,
  [HEADERS.channel]: channel.name,
  [HEADERS.clientContract]: channel.contractVersion,
});

const GENERATED_NOTE = (client, channel) =>
  `GENERATED by packages/clients/scripts/generate.js from channels.json (client: ${client.id}, channel: ${channel.name}). ` +
  `Do not hand-edit — run \`npm run clients:generate\` instead. CI fails if this drifts from channels.json. ` +
  `No credential is needed: the hub serves two read-only tools anonymously.`;

// --- writers, one per declared format --------------------------------------

// Claude Code / Claude Desktop style: an mcpServers object.
function writeMcpJson(client, channel) {
  return `${JSON.stringify(
    {
      _comment: GENERATED_NOTE(client, channel),
      mcpServers: {
        [SERVER_NAME]: {
          type: 'http',
          url: channel.url,
          headers: headersFor(client, channel),
        },
      },
    },
    null,
    2
  )}\n`;
}

// Codex CLI style: TOML.
//
// Caveat worth stating rather than hiding: the exact key names a given Codex version
// wants for a REMOTE MCP server are not something this repository can verify, so treat
// the shape below as a starting point and check it against the version you run. That
// this is the only place to change it is the point of generating rather than
// hand-writing: one edit here fixes every channel at once.
function writeToml(client, channel) {
  // Only simple string values are emitted, so basic double-quoting is sufficient. A
  // value needing escapes would be a bug in the manifest, not something to paper over.
  const quote = (v) => {
    const s = String(v);
    if (/["\\\n]/.test(s)) throw new Error(`value ${JSON.stringify(s)} needs TOML escaping; the manifest should not contain it`);
    return `"${s}"`;
  };
  const key = SERVER_NAME.replace(/-/g, '_');
  const lines = [
    `# ${GENERATED_NOTE(client, channel)}`,
    '',
    `[mcp_servers.${key}]`,
    `url = ${quote(channel.url)}`,
    '',
    `[mcp_servers.${key}.http_headers]`,
  ];
  for (const [h, v] of Object.entries(headersFor(client, channel))) lines.push(`${quote(h)} = ${quote(v)}`);
  lines.push('');
  return lines.join('\n');
}

const WRITERS = { 'mcp-json': writeMcpJson, toml: writeToml };

// The config every declared client should currently have, as text.
function renderAll(channel, only = null) {
  const out = [];
  for (const client of CLIENTS) {
    if (only && client.id !== only) continue;
    const writer = WRITERS[client.format];
    if (!writer) throw new Error(`client "${client.id}" declares format "${client.format}", which has no writer in generate.js`);
    out.push({
      client,
      file: path.join(ROOT, client.id, client.configPath),
      relative: `${client.id}/${client.configPath}`,
      content: writer(client, channel),
    });
  }
  if (only && out.length === 0) throw new Error(`unknown client "${only}" — the contract declares ${CLIENTS.map((c) => c.id).join(', ')}`);
  return out;
}

const originOf = (url) => {
  const u = new URL(url);
  return `${u.protocol}//${u.host}`;
};

async function fetchDeployedIdentity(channel, timeoutMs) {
  const versionUrl = `${originOf(channel.url)}${ENDPOINTS.version}`;
  try {
    const res = await fetch(versionUrl, { signal: AbortSignal.timeout(timeoutMs) });
    if (!res.ok) return { reachable: false, reason: `${versionUrl} returned ${res.status}` };
    return { reachable: true, identity: await res.json(), versionUrl };
  } catch (err) {
    return { reachable: false, reason: `${versionUrl}: ${err.message}` };
  }
}

async function main() {
  const manifest = readJson(CHANNELS_PATH);
  const channel = resolveChannel(manifest);
  const only = arg('client');
  const timeoutMs = Number(arg('timeout-ms', '10000'));
  const problems = [];

  // --- structural checks, no network needed -------------------------------
  if (channel.requireHttps !== false && !channel.url.startsWith('https://')) {
    problems.push(`channel "${channel.name}" requires https but its url is ${channel.url}`);
  }
  if (HARDENED_CHANNELS.includes(channel.name) && channel.requireHttps === false) {
    problems.push(`channel "${channel.name}" is hardened and must not set requireHttps: false`);
  }
  if (!channel.url.endsWith(ENDPOINTS.mcp)) {
    problems.push(`channel "${channel.name}" url should end with the contract's MCP path (${ENDPOINTS.mcp}): ${channel.url}`);
  }
  if (!/^[0-9a-f]{12}$/.test(channel.contractDigest || '')) {
    problems.push(`channel "${channel.name}" has a malformed contractDigest: ${channel.contractDigest}`);
  }

  const rendered = renderAll(channel, only);
  const drifted = rendered.filter((r) => !fs.existsSync(r.file) || fs.readFileSync(r.file, 'utf8') !== r.content);

  if (flag('print')) {
    console.log(
      JSON.stringify(
        {
          channel: channel.name,
          url: channel.url,
          pinnedContract: { version: channel.contractVersion, digest: channel.contractDigest },
          thisCheckout: { version: CONTRACT_VERSION, digest: contractDigest() },
          clients: rendered.map((r) => ({ id: r.client.id, host: r.client.host, config: r.relative, inSync: !drifted.includes(r) })),
        },
        null,
        2
      )
    );
    return;
  }

  // --- write --------------------------------------------------------------
  if (flag('write')) {
    if (problems.length) {
      for (const p of problems) console.error(`FAIL  ${p}`);
      process.exitCode = 1;
      return;
    }
    for (const r of rendered) {
      fs.mkdirSync(path.dirname(r.file), { recursive: true });
      fs.writeFileSync(r.file, r.content);
      console.log(`ok    ${r.relative} ${drifted.includes(r) ? 'updated' : 'unchanged'} -> ${channel.url}`);
    }
    console.log(`ok    ${rendered.length} client config(s) generated for channel "${channel.name}"`);
    return;
  }

  // --- sync-pin (CD, after a verified deploy) -----------------------------
  if (flag('sync-pin')) {
    const deployed = await fetchDeployedIdentity(channel, timeoutMs);
    if (!deployed.reachable) {
      console.error(`FAIL  cannot read the deployed contract: ${deployed.reason}`);
      console.error('      --sync-pin must never guess. A pin is only advanced from a hub that answered.');
      process.exitCode = 1;
      return;
    }

    const { contractVersion, contractDigest: deployedDigest } = deployed.identity;
    if (!/^[0-9a-f]{12}$/.test(deployedDigest || '')) {
      console.error(`FAIL  the deployed hub reported a malformed contract digest: ${deployedDigest}`);
      process.exitCode = 1;
      return;
    }
    // The deployed hub must be serving THIS checkout's contract. If not, the pipeline is
    // mid-rollout or someone deployed another commit, and advancing the pin would record
    // a contract these clients were never generated from.
    if (deployedDigest !== contractDigest()) {
      console.error(`FAIL  the deployed hub serves contract ${deployedDigest} but this checkout builds ${contractDigest()}`);
      console.error('      Refusing to pin a contract these clients were not generated from.');
      process.exitCode = 1;
      return;
    }

    const unchanged = channel.contractDigest === deployedDigest && channel.contractVersion === contractVersion;
    manifest.channels[channel.name].contractDigest = deployedDigest;
    manifest.channels[channel.name].contractVersion = contractVersion;
    fs.writeFileSync(CHANNELS_PATH, `${JSON.stringify(manifest, null, 2)}\n`);

    // Regenerate from the freshly pinned channel, so the configs and the pin move together.
    for (const r of renderAll({ ...channel, contractVersion, contractDigest: deployedDigest })) {
      fs.mkdirSync(path.dirname(r.file), { recursive: true });
      fs.writeFileSync(r.file, r.content);
    }
    console.log(
      unchanged
        ? `ok    channel "${channel.name}" pin already at ${deployedDigest} (${contractVersion}) — nothing to commit`
        : `ok    channel "${channel.name}" pin advanced to ${deployedDigest} (${contractVersion}); ${CLIENTS.length} client config(s) regenerated`
    );
    return;
  }

  // --- check (CI) ---------------------------------------------------------
  // Read-only by design: a check that repaired what it was checking would let a pull
  // request pass by rewriting the evidence.
  for (const r of drifted) {
    problems.push(`${r.relative} has drifted from channels.json (channel "${channel.name}"). Run \`npm run clients:generate\` and commit.`);
  }

  // The pin must describe the contract this repository builds. If it does not, someone
  // changed the tool surface without regenerating the clients — the cascade this whole
  // mechanism exists to catch.
  const localVerdict = compareContract(
    { contractVersion: channel.contractVersion, contractDigest: channel.contractDigest },
    { contractVersion: CONTRACT_VERSION, contractDigest: contractDigest() }
  );
  if (localVerdict.verdict !== 'ok') {
    problems.push(
      `channel "${channel.name}" is pinned to contract ${channel.contractDigest} (${channel.contractVersion}) but this checkout builds ` +
        `${contractDigest()} (${CONTRACT_VERSION}) — ${localVerdict.reason}. The tool surface changed without regenerating the clients.`
    );
  }

  // Then, if the channel is reachable, check the deployed hub too. Unreachable is NOT a
  // failure: a fork's pull request has no route to Azure, and CI must not depend on one.
  const deployed = await fetchDeployedIdentity(channel, timeoutMs);
  if (!deployed.reachable) {
    console.log(`note  channel "${channel.name}" is not reachable from here, so the deployed digest was not checked (${deployed.reason})`);
  } else {
    const verdict = compareContract({ contractVersion: channel.contractVersion, contractDigest: channel.contractDigest }, deployed.identity);
    if (verdict.verdict === 'breaking') {
      problems.push(`BREAKING: ${deployed.versionUrl} — ${verdict.reason}. These clients cannot talk to that hub; they must be upgraded.`);
    } else if (verdict.verdict !== 'ok') {
      problems.push(
        `channel "${channel.name}" pin (${channel.contractDigest}) does not match the deployed hub (${deployed.identity.contractDigest}) — ` +
          `${verdict.reason}. Run --sync-pin after the deploy has been verified.`
      );
    } else {
      console.log(`ok    deployed hub at ${deployed.versionUrl} serves the pinned contract ${deployed.identity.contractDigest}`);
      console.log(`ok    deployed commit ${deployed.identity.commit} on channel ${deployed.identity.channel}`);
    }
  }

  if (problems.length) {
    for (const p of problems) console.error(`FAIL  ${p}`);
    process.exitCode = 1;
    return;
  }
  console.log(
    `ok    channel "${channel.name}" is in sync across ${rendered.length} client(s) — contract ${channel.contractDigest} (${channel.contractVersion})`
  );
}

module.exports = { renderAll, headersFor, resolveChannel, writeMcpJson, writeToml, WRITERS, SERVER_NAME, CHANNELS_PATH, getClient };

if (require.main === module) {
  main().catch((err) => {
    console.error(`FAIL  ${err.message}`);
    process.exit(1);
  });
}
